//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableOfUdtOracle.Domain.Entities
{
    using Oracle.ManagedDataAccess.Types;
    using System.Xml.Schema;
    using System.Xml.Serialization;


    public class TYPE_DEMANDE_DOC_TAB : INullable, IOracleCustomType, IXmlSerializable
    {

        private bool m_IsNull;

        private TYPE_DEMANDE_DOC_REC[] m_TYPE_DEMANDE_DOC_RESO_REC;

        public TYPE_DEMANDE_DOC_TAB()
        {
            // TODO : Add code to initialise the object
        }

        public TYPE_DEMANDE_DOC_TAB(string str)
        {
            // TODO : Add code to initialise the object based on the given string 
        }

        public virtual bool IsNull
        {
            get
            {
                return this.m_IsNull;
            }
        }

        public static TYPE_DEMANDE_DOC_TAB Null
        {
            get
            {
                TYPE_DEMANDE_DOC_TAB obj = new TYPE_DEMANDE_DOC_TAB();
                obj.m_IsNull = true;
                return obj;
            }
        }

        [OracleArrayMappingAttribute()]
        public virtual TYPE_DEMANDE_DOC_REC[] Value
        {
            get
            {
                return this.m_TYPE_DEMANDE_DOC_RESO_REC;
            }
            set
            {
                this.m_TYPE_DEMANDE_DOC_RESO_REC = value;
            }
        }

        public virtual void FromCustomObject(Oracle.ManagedDataAccess.Client.OracleConnection con, object pUdt)
        {
            OracleUdt.SetValue(con, pUdt, 0, this.m_TYPE_DEMANDE_DOC_RESO_REC);
        }

        public virtual void ToCustomObject(Oracle.ManagedDataAccess.Client.OracleConnection con, object pUdt)
        {
            this.m_TYPE_DEMANDE_DOC_RESO_REC = ((TYPE_DEMANDE_DOC_REC[])(OracleUdt.GetValue(con, pUdt, 0)));
        }

        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            // TODO : Read Serialized Xml Data
        }

        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            // TODO : Serialize object to xml data
        }

        public virtual XmlSchema GetSchema()
        {
            // TODO : Implement GetSchema
            return null;
        }

        public override string ToString()
        {
            // TODO : Return a string that represents the current object
            return "";
        }

        public static TYPE_DEMANDE_DOC_TAB Parse(string str)
        {
            // TODO : Add code needed to parse the string and get the object represented by the string
            return new TYPE_DEMANDE_DOC_TAB();
        }
    }

    // Factory to create an object for the above class
    [OracleCustomTypeMappingAttribute("C##STEPHANE.TYPE_DEMANDE_DOC_TAB")]
    public class TYPE_DEMANDE_DOC_RESO_TABFactory : IOracleCustomTypeFactory, IOracleArrayTypeFactory
    {

        public virtual IOracleCustomType CreateObject()
        {
            TYPE_DEMANDE_DOC_TAB obj = new TYPE_DEMANDE_DOC_TAB();
            return obj;
        }

        public virtual System.Array CreateArray(int length)
        {
            TYPE_DEMANDE_DOC_REC[] collElem = new TYPE_DEMANDE_DOC_REC[length];
            return collElem;
        }

        public virtual System.Array CreateStatusArray(int length)
        {
            return null;
        }
    }
}
