//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableOfUdtOracle.Domain.Entities
{
    using Oracle.ManagedDataAccess.Types;
    using System.Xml.Schema;
    using System.Xml.Serialization;


    public class TYPE_DEMANDE_REC : INullable, IOracleCustomType, IXmlSerializable {
        
        private bool m_IsNull;
        
        private string m_PRENOM;        
        
        private string m_REQUETE_ID;
        
        private string m_NOM;
        
        public TYPE_DEMANDE_REC() {
            // TODO : Add code to initialise the object
        }
        
        public TYPE_DEMANDE_REC(string str) {
            // TODO : Add code to initialise the object based on the given string 
        }
        
        public virtual bool IsNull {
            get {
                return this.m_IsNull;
            }
        }
        
        public static TYPE_DEMANDE_REC Null {
            get {
                TYPE_DEMANDE_REC obj = new TYPE_DEMANDE_REC();
                obj.m_IsNull = true;
                return obj;
            }
        }
        
        [OracleObjectMappingAttribute("PRENOM")]
        public string PRENOM {
            get {
                return this.m_PRENOM;
            }
            set {
                this.m_PRENOM = value;
            }
        }
        
        //[OracleObjectMappingAttribute("COURRIEL")]
        //public string COURRIEL {
        //    get {
        //        return this.m_COURRIEL;
        //    }
        //    set {
        //        this.m_COURRIEL = value;
        //    }
        //}
        
        [OracleObjectMappingAttribute("REQUETE_ID")]
        public string REQUETE_ID {
            get {
                return this.m_REQUETE_ID;
            }
            set {
                this.m_REQUETE_ID = value;
            }
        }
        
        [OracleObjectMappingAttribute("NOM")]
        public string NOM {
            get {
                return this.m_NOM;
            }
            set {
                this.m_NOM = value;
            }
        }
        
        public virtual void FromCustomObject(Oracle.ManagedDataAccess.Client.OracleConnection con, object pUdt) {
            Oracle.ManagedDataAccess.Types.OracleUdt.SetValue(con, pUdt, "PRENOM", this.PRENOM);
            //Oracle.ManagedDataAccess.Types.OracleUdt.SetValue(con, pUdt, "COURRIEL", this.COURRIEL);
            Oracle.ManagedDataAccess.Types.OracleUdt.SetValue(con, pUdt, "REQUETE_ID", this.REQUETE_ID);
            Oracle.ManagedDataAccess.Types.OracleUdt.SetValue(con, pUdt, "NOM", this.NOM);
        }
        
        public virtual void ToCustomObject(Oracle.ManagedDataAccess.Client.OracleConnection con, object pUdt) {
            this.PRENOM = ((string)(Oracle.ManagedDataAccess.Types.OracleUdt.GetValue(con, pUdt, "PRENOM")));
            //this.COURRIEL = ((string)(Oracle.ManagedDataAccess.Types.OracleUdt.GetValue(con, pUdt, "COURRIEL")));
            this.REQUETE_ID = ((string)(Oracle.ManagedDataAccess.Types.OracleUdt.GetValue(con, pUdt, "REQUETE_ID")));
            this.NOM = ((string)(Oracle.ManagedDataAccess.Types.OracleUdt.GetValue(con, pUdt, "NOM")));
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            // TODO : Read Serialized Xml Data
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            // TODO : Serialize object to xml data
        }
        
        public virtual XmlSchema GetSchema() {
            // TODO : Implement GetSchema
            return null;
        }
        
        public override string ToString() {
            // TODO : Return a string that represents the current object
            return "";
        }
        
        public static TYPE_DEMANDE_REC Parse(string str) {
            // TODO : Add code needed to parse the string and get the object represented by the string
            return new TYPE_DEMANDE_REC();
        }
    }
    
    // Factory to create an object for the above class
    [OracleCustomTypeMappingAttribute("C##STEPHANE.TYPE_DEMANDE_REC")]
    public class TYPE_DEMANDE_RESO_RECFactory : IOracleCustomTypeFactory {
        
        public virtual IOracleCustomType CreateObject() {
            TYPE_DEMANDE_REC obj = new TYPE_DEMANDE_REC();
            return obj;
        }
    }
}
